# server port
server:
  port: 8081

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/indigo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: board_mb
    password: 1234

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml # query?? xml? ??
  config-location: classpath:mybatis-config.xml # mybatis ?? ??